INSERT INTO PUBLIC.PRODUCT_TYPE (TYPE_NAME) VALUES ('Hoodie');
INSERT INTO PUBLIC.PRODUCT_TYPE (TYPE_NAME) VALUES ('Shirt');
INSERT INTO PUBLIC.PRODUCT_TYPE (TYPE_NAME) VALUES ('Pants');

INSERT INTO PUBLIC.PRODUCT (PRODUCT_TYPE_ID, NAME, SIZE, COLOR) VALUES (1, 'Prada', 'M', 'Black');
INSERT INTO PUBLIC.PRODUCT (PRODUCT_TYPE_ID, NAME, SIZE, COLOR) VALUES (2, 'Gucci', 'L', 'White');
INSERT INTO PUBLIC.PRODUCT (PRODUCT_TYPE_ID, NAME, SIZE, COLOR) VALUES (3, 'Diesel', 'XL', 'Red');

