INSERT INTO PUBLIC.PRODUCT_TYPE (TYPE_NAME) VALUES ('Hoodie');
INSERT INTO PUBLIC.PRODUCT_TYPE (TYPE_NAME) VALUES ('Shirt');
INSERT INTO PUBLIC.PRODUCT_TYPE (TYPE_NAME) VALUES ('Pants');

INSERT INTO PUBLIC.PRODUCT (PRODUCT_TYPE_ID, NAME, SIZE, COLOR) VALUES (1, 'Prada', 'M', 'Black');
INSERT INTO PUBLIC.PRODUCT (PRODUCT_TYPE_ID, NAME, SIZE, COLOR) VALUES (2, 'Gucci', 'L', 'White');
INSERT INTO PUBLIC.PRODUCT (PRODUCT_TYPE_ID, NAME, SIZE, COLOR) VALUES (3, 'Diesel', 'XL', 'Red');

INSERT INTO PUBLIC.CUSTOMER (FIRST_NAME, LAST_NAME, PHONE) VALUES ('John', 'Doe', '123456789');
INSERT INTO PUBLIC.CUSTOMER (FIRST_NAME, LAST_NAME, PHONE) VALUES ('Jane', 'Smith', '987654321');

INSERT INTO PUBLIC.SALE (PRODUCT_ID, CUSTOMER_ID, SALE_DATE, SALE_PRICE) VALUES (1, 1, '2025-12-21', 99.00);
INSERT INTO PUBLIC.SALE (PRODUCT_ID, CUSTOMER_ID, SALE_DATE, SALE_PRICE) VALUES (2, 2, '2025-12-22', 129.99);

